name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
